services:
  catscan:
    build:
      context: .
      args:
        BASE_IMAGE: ${CATSCAN_BASE_IMAGE:-alpine:latest}
        CATS_SCANNER_VERSION: ${CATSCAN_VERSION:-0.1.0}
        TRIVY_VERSION: ${TRIVY_VERSION:-0.69.3}
        TRIVY_SHA256: ${TRIVY_SHA256:-1816b632dfe529869c740c0913e36bd1629cb7688bd5634f4a858c1d57c88b75}
        DOCKLE_VERSION: ${DOCKLE_VERSION:-0.4.15}
        DOCKLE_SHA256: ${DOCKLE_SHA256:-8bfc9183d1d3d67800edb45bea4bb63ddf1d28bec5f89944075a07007d79caad}
        HELM_VERSION: ${HELM_VERSION:-4.2.3}
        HELM_SHA256: ${HELM_SHA256:-e9b88b4ee95b18c706839c28d3a0220e5bc470e9cd9262410c90793c45ff8b7c}
        GRYPE_DB_REFRESH: ${GRYPE_DB_REFRESH:-manual}
        GRYPE_DB_UPDATE_URL: ${GRYPE_DB_UPDATE_URL:-https://grype.anchore.io/databases/v6/latest.json}
    image: ${CATSCAN_IMAGE:-catscan:local}
    working_dir: /workspace
    command: ["/usr/local/bin/catscan-self-test"]
