apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-diagram-demo.fullname" . }}-config
  labels:
    {{- include "helm-diagram-demo.labels" . | nindent 4 }}
data:
  LOG_LEVEL: "info"
  API_BASE_URL: "http://{{ include "helm-diagram-demo.fullname" . }}-api:{{ .Values.api.servicePort }}"
  CACHE_HOST: "{{ include "helm-diagram-demo.fullname" . }}-redis"

