apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-diagram-demo.fullname" . }}-credentials
  labels:
    {{- include "helm-diagram-demo.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_USER: catalog
  DATABASE_PASSWORD: replace-me

