apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: catscan-smoke
  template:
    metadata:
      labels:
        app.kubernetes.io/name: catscan-smoke
    spec:
      containers:
        - name: catscan-smoke
          image: registry.invalid/catscan-smoke:1.0
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 64Mi
