import {can, type PageData} from '../api';
import {Dialog} from '../components/Form';
import {AdminTabs, Heading, Post, Saved, SelectRows} from './admin_shared';

export function Page({data}: {data: PageData}) {
  const roleManage = can(data, 'role.manage'), userManage = can(data, 'user.manage');
  return <><Heading title="Accounts and roles" description="Identity, functional permissions, and service access are managed independently."/><AdminTabs data={data} selected="accounts"/><Saved data={data} message="Service information saved successfully."/>
    <div className="admin-grid">{userManage && <section className="panel padded admin-card"><h2>Create local account</h2><Post data={data} action="/admin/users"><label>Username<input name="username" required/></label><label>Display name<input name="display_name" required/></label><label>Temporary password<input type="password" name="password" minLength={14} required autoComplete="new-password"/></label><button>Create account</button></Post></section>}
    {roleManage && <><section className="panel padded admin-card"><h2>Assign role</h2><Post data={data} action="/admin/assignments"><SelectRows label="User" name="user_id" rows={data.users}/><SelectRows label="Role" name="role_id" rows={data.roles}/><SelectRows label="Service scope (Ctrl/Cmd-click for multiple; leave blank for group/global scope)" name="service_ids" rows={data.services} multiple/><SelectRows label="Group scope" name="group_id" rows={data.groups} empty="No group scope"/><button>Assign</button></Post></section>
    <section className="panel padded admin-card role-builder"><h2>Create custom role</h2><Post data={data} action="/admin/roles"><div className="role-basics"><label>Name<input name="name" required/></label><label>Description<input name="description"/></label></div><fieldset className="permission-fieldset"><legend>Permissions</legend><div className="permission-grid">{Object.entries(data.permission_catalog || {}).map(([key, description]) => <label key={key} className="permission-option" title={String(description)} tabIndex={0}><input type="checkbox" name="permissions" value={key}/><span className="permission-name">{key}</span></label>)}</div></fieldset><button>Create role</button></Post></section></>}</div>
    <section className="panel padded admin-card"><h2>Create service group</h2>{roleManage && <Post data={data} action="/admin/groups"><label>Name<input name="name" required maxLength={120}/></label><label>Description<input name="description"/></label><button>Create group</button></Post>}<div className="group-summary-grid" aria-label="Service groups">{(data.group_summaries || []).map((row: any) => <article key={row.group.id} className="group-summary-card"><strong>{row.group.name}</strong><span>{row.active_services} Active Services</span><small>{row.service_count} total services{row.group.description && ` · ${row.group.description}`}</small></article>)}</div></section>
    <section className="panel padded user-account-table"><h2>User access overview</h2><p className="muted">Matching numbered chips form an access chain: Role → Group → Service scope. Expand permissions for the detailed list.</p><div className="table-wrap"><table><thead><tr>{['User', 'Source', 'Status', 'Last Logon', 'Roles', 'Groups', 'Service scope', 'Permissions', 'Account Actions'].map(title => <th key={title}>{title}</th>)}</tr></thead><tbody>{(data.user_rows || []).map((row: any) => {const user = row.user; return <tr key={user.id}><td><strong>{user.display_name}</strong><br/><code>{user.username}</code></td><td>{user.auth_source}</td><td>{user.enabled ? 'Enabled' : 'Disabled'}</td><td>{user.last_login_at || 'Never'}</td><td>{row.assignments.length ? row.assignments.map((assignment: any, index: number) => <div key={assignment.id} className="access-chip"><strong>{index + 1}. {assignment.role}</strong>{roleManage && <Post data={data} className="inline-form" action={`/admin/assignments/${assignment.id}/delete`}><button className="link-button">Remove</button></Post>}</div>) : 'None'}</td>{['group', 'service'].map(field => <td key={field}>{row.assignments.length ? row.assignments.map((assignment: any, index: number) => <div key={assignment.id} className="access-chip">{index + 1}. {assignment[field]}</div>) : 'None'}</td>)}<td>{row.permissions.length ? <details className="permission-details"><summary>{row.permissions.length} permissions</summary><ul>{row.permissions.map((permission: string) => <li key={permission}><code>{permission}</code><span>{data.permission_catalog[permission]}</span></li>)}</ul></details> : 'None'}</td><td><div className="account-actions">{userManage && !user.is_self && <><Post data={data} action={`/admin/users/${user.id}/toggle`}><button className="account-action-button">{user.enabled ? 'Disable' : 'Enable'}</button></Post><Dialog button="Delete" title="Delete account" buttonClass="secondary-button account-action-button"><Post data={data} action={`/admin/users/${user.id}/delete`}><p>This permanently removes <strong>{user.display_name}</strong> ({user.username}) from CATS. Historical audit records are retained.</p><button>Delete account</button></Post></Dialog></>}{userManage && user.auth_source === 'local' && <Dialog button="Reset password" title="Reset password" buttonClass="secondary-button account-action-button"><Post data={data} action={`/admin/users/${user.id}/reset-password`}><p>Set a temporary password for {user.display_name}.</p><label>Temporary password<input type="password" name="temporary_password" minLength={14} required autoComplete="new-password"/></label><button>Reset password</button></Post></Dialog>}</div></td></tr>;})}</tbody></table></div></section></>;
}
