import {createContext, useCallback, useContext, useEffect, useRef, useState, type ReactNode} from 'react';
import {can, type PageData} from '../api';
import {AdminTabs, Heading, Hidden, Post, Saved} from './admin_shared';

type Field = [string, string, string?, boolean?];
function TextFields({fields, values = {}}: {fields: Field[]; values?: any}) {
  return <>{fields.map(([name, label, type = 'text', required]) => <label key={name}>{label}{type === 'textarea' ? <textarea name={name} defaultValue={values[name] || ''}/> : <input name={name} type={type} required={required} readOnly={name === 'redirect_uri' || name === 'post_logout_redirect_uri'} defaultValue={type === 'password' || type === 'file' ? undefined : values[name] || ''} autoComplete={type === 'password' ? 'new-password' : undefined}/>}</label>)}</>;
}
function Choice({name, label, options, value}: {name: string; label: string; options: (string | [string, string])[]; value?: any}) {
  return <label>{label}<select name={name} defaultValue={value ?? (Array.isArray(options[0]) ? options[0][0] : options[0])}>{options.map(option => {const [key, text] = Array.isArray(option) ? option : [option, option]; return <option key={key} value={key}>{text}</option>;})}</select></label>;
}
function Check({name, label, checked, value = 'true'}: {name: string; label: string; checked?: boolean; value?: string}) {return <label className="checkbox-label"><input name={name} type="checkbox" value={value} defaultChecked={checked}/>{label}</label>;}
const warningLabels: [string, string][] = [['critical_high', 'Critical / High findings'], ['kev', 'KEV'], ['watchlist', 'Dependency Watchlist'], ['poam', 'Open POA&M'], ['kind', 'Failed Kind validation'], ['missing_evidence', 'Missing Evidence']];
const categories = [['general', 'General'], ['identity-access', 'Identity & Access'], ['security', 'Security'], ['integrations', 'Integrations'], ['data', 'Data']];
const SettingsContext = createContext({category: 'general', query: ''});
function Block({group, title, terms = '', children}: {group: string; title: string; terms?: string; children: ReactNode}) {
  const {category, query} = useContext(SettingsContext);
  const visible = query.trim() ? `${title} ${terms}`.toLocaleLowerCase().includes(query.toLocaleLowerCase().trim()) : category === group;
  return <section hidden={!visible} className="panel padded config-subpanel"><h2>{title}</h2>{children}</section>;
}

function RepositoryForm({data, id, definition, policy = {}}: {data: PageData; id?: string; definition?: any; policy?: any}) {
  const [tls, setTls] = useState(policy.verify_tls !== false), [packages, setPackages] = useState(policy.verify_packages !== false);
  return <Post data={data} action="/admin/configuration/repositories" className="repository-policy-form"><Hidden name="action" value={id ? 'save' : 'add'}/>{id && <Hidden name="edit_os_id" value={id}/>}<div className="config-grid">{id ? <><label>OS identifier<input value={id} disabled/></label><label>Package manager<input value={definition.package_manager} disabled/></label>{data.custom_os?.includes(id) && <><Hidden name="display_name" value={definition.name}/><Hidden name="package_manager" value={definition.package_manager}/></>}</> : <><label>OS identifier<input name="os_id" required pattern="[a-z0-9][a-z0-9._-]{0,31}" placeholder="my-linux"/></label><label>Display name<input name="display_name" required maxLength={120}/></label><Choice name="package_manager" label="Package manager" options={data.package_managers || []}/></>}<Choice name="mode" label="Repository mode" options={['default', 'custom'].map(value => [value, value === 'default' ? 'Image-defined' : 'Custom mirror']) as [string, string][]} value={policy.mode || 'default'}/><label>Repository URL<input name="url" type="url" defaultValue={policy.url || ''} placeholder="https://mirror.example.invalid/os"/></label><label className="checkbox-label"><input type="checkbox" name="verify_tls" value="true" checked={tls} onChange={event => setTls(event.target.checked)}/><Hidden name="verify_tls" value="false"/>Verify repository TLS certificates</label><label className="checkbox-label"><input type="checkbox" name="verify_packages" value="true" checked={packages} onChange={event => setPackages(event.target.checked)}/><Hidden name="verify_packages" value="false"/>Verify package signatures</label></div><p className="repository-policy-warning" role="alert">{!tls && !packages ? 'Warning: TLS certificate and package signature verification are disabled for this repository.' : !tls ? 'Warning: TLS certificate verification is disabled for this repository.' : !packages ? 'Warning: package signature verification is disabled for this repository.' : ''}</p><button>{id ? 'Save OS policy' : 'Add operating system'}</button></Post>;
}

export function Page({data}: {data: PageData}) {
  const initialCategory = useCallback(() => {const hash = window.location.hash.slice(1), saved = sessionStorage.getItem('cats-settings-category'); return categories.some(([key]) => key === hash) ? hash : data.edit_os_id ? 'integrations' : categories.some(([key]) => key === saved) ? saved! : 'general';}, [data.edit_os_id]);
  const [category, setCategory] = useState(initialCategory), [query, setQuery] = useState('');
  const [mapping, setMapping] = useState<any>(null), [mappingOpen, setMappingOpen] = useState(false);
  const [registry, setRegistry] = useState<any>(null), [registryOpen, setRegistryOpen] = useState(false);
  const panel = useRef<HTMLElement>(null), [noMatches, setNoMatches] = useState(false);
  useEffect(() => {const listener = () => {setCategory(initialCategory()); setQuery('');}; window.addEventListener('hashchange', listener); return () => window.removeEventListener('hashchange', listener);}, [initialCategory]);
  useEffect(() => {if (!query) sessionStorage.setItem('cats-settings-category', category);}, [category, query]);
  useEffect(() => {setNoMatches(!!query.trim() && !panel.current?.querySelector('.config-subpanel:not([hidden])'));}, [category, query]);
  const config = data.configuration || {}, oidc = data.oidc || {}, signing = data.signing || {}, validator = data.validator || {};
  // Keep editor state outside category blocks so filtering never exposes or populates stored secrets.
  return <SettingsContext.Provider value={{category, query}}><div className="admin-workspace settings-workspace"><Heading title="Settings" description="Global runtime preferences for this CATS portal."/><AdminTabs data={data} selected="configuration"/><section ref={panel} className="panel padded configuration-panel"><Saved data={data} message="Configuration saved successfully."/><p className="muted">These settings apply to the portal instance. Group and service governance remains managed in the policy tabs.</p><nav className="settings-nav" aria-label="Settings categories">{categories.map(([key, title]) => <a href={`#${key}`} key={key} aria-current={!query && category === key ? 'page' : undefined} onClick={() => {setCategory(key); setQuery('');}}>{title}</a>)}</nav><label className="settings-search-label" htmlFor="settings-search">Search settings</label><input id="settings-search" type="search" value={query} onChange={event => setQuery(event.target.value)} placeholder="Search settings..."/><small className="muted">Search section names and fields across all categories.</small>{noMatches && <p className="muted" role="status">No matching settings found.</p>}
  {!can(data, 'config.manage') ? <p>You do not have permission to change global settings.</p> : <>
  <Block group="general" title="Portal Preferences" terms="display timezone date format time format"><Post data={data} action="/admin/configuration"><div className="config-grid"><Choice name="display_timezone" label="Display timezone" options={data.timezones || []} value={config.display_timezone}/><Choice name="date_format" label="Date format" options={data.date_formats || []} value={config.date_format}/><Choice name="time_format" label="Time format" options={data.time_formats || []} value={config.time_format}/><Hidden name="identity_mode" value={config.identity_mode}/></div><div className="config-actions"><button>Save configuration</button><span>Changes are recorded in the audit history.</span></div></Post></Block>
  <Block group="identity-access" title="Authentication" terms="identity mode local accounts organizational OIDC recovery access"><p>Choose local accounts, organizational OIDC, or both for recovery access.</p><Post data={data} action="/admin/configuration"><Hidden name="display_timezone" value={config.display_timezone}/><Hidden name="date_format" value={config.date_format}/><Hidden name="time_format" value={config.time_format}/><Choice name="identity_mode" label="Identity mode" value={config.identity_mode} options={ [['local', 'Local accounts'], ['oidc', 'OIDC'], ['both', 'Both local and OIDC']] }/><button>Save authentication mode</button></Post></Block>
  <Block group="security" title="Remediation" terms="enable patch worker registry trust validation"><p>Enable service remediation only after the patch worker, registry, trust, and validation infrastructure have been reviewed. Existing jobs continue to a safe terminal state and history remains available.</p><Post data={data} action="/admin/configuration/remediation"><Check name="enabled" label="Enable Remediation" checked={config.remediation_enabled === 'true'}/><button>Save Remediation setting</button></Post></Block>
  <Block group="security" title="Image signing" terms="private key public key password signature cosign"><p>Sign and verify images pushed by portal patch jobs. Download-only jobs and pipeline scans are excluded. Signatures stay in your registry; no public transparency-log connection is required.</p>{signing.error && <p role="alert">{signing.error}</p>}<p>Status: <strong>{signing.enabled ? 'Enabled' : 'Disabled'}</strong>{signing.configured && <> · Key <code>{signing.fingerprint}</code> · Updated {signing.updated_at} · <a href="/admin/configuration/signing/public-key">Download public key</a></>}</p><Post data={data} action="/admin/configuration/signing" upload><div className="config-grid"><label>Private key<input type="file" name="private_key" accept=".key,.pem"/><small>Cosign PEM key, up to 32 KiB. Leave blank to keep the saved key. Stored encrypted and never displayed.</small></label><label>Public key<input type="file" name="public_key" accept=".pub,.pem"/><small>Optional: derived from the private key; uploaded keys must match.</small></label><label>Private key password<input type="password" name="key_password" autoComplete="new-password"/><small>Supply with a new private key. Stored encrypted.</small></label><Check name="enabled" label="Require signing for portal patch pushes" checked={signing.enabled}/></div><p>Publishing with signing enabled requires the image-signing permission. A job succeeds only after signature verification. Key storage uses the server's CATS_CONFIG_ENCRYPTION_KEY.</p><div className="config-actions"><button name="action" value="save">Save signing configuration</button>{signing.configured && <button name="action" value="remove">Remove signing keys and disable signing</button>}</div></Post></Block>
  <Block group="identity-access" title="OIDC identity provider" terms="provider issuer client ID client secret scopes username email groups roles public browser redirect logout"><p>Client secrets are encrypted at rest and never displayed after saving.</p>{data.oidc_result && <p role="status">{data.oidc_result}</p>}<Post data={data} action="/admin/configuration/oidc"><div className="config-grid"><TextFields values={oidc} fields={ [['provider_name', 'Provider name'], ['issuer', 'Issuer URL', 'url', true], ['client_id', 'Client ID', 'text', true]] }/><label>Client secret{oidc.client_secret_configured && <small>Configured. Leave blank to keep it.</small>}<input name="client_secret" type="password" autoComplete="new-password" placeholder={oidc.client_secret_configured ? 'Replace secret' : 'Client secret'}/></label></div><details className="advanced-settings"><summary>Advanced OIDC settings</summary><div className="config-grid"><TextFields values={{...oidc, scopes: oidc.scopes || 'openid profile email', username_claim: oidc.username_claim || 'preferred_username', email_claim: oidc.email_claim || 'email'}} fields={ [['scopes', 'Scopes'], ['username_claim', 'Username claim'], ['email_claim', 'Email claim'], ['groups_claim', 'Groups claim (optional)'], ['roles_claim', 'Roles claim (optional)'], ['browser_issuer', 'Public issuer URL (optional)', 'url']] }/></div></details><div className="config-grid callback-fields"><TextFields values={oidc} fields={ [['redirect_uri', 'Redirect URI (register with provider)', 'url'], ['post_logout_redirect_uri', 'Post-logout redirect URI', 'url']] }/></div><div className="config-actions"><button name="action" value="save">Save OIDC settings</button><button name="action" value="test">Test Connection</button></div></Post></Block>
  <Block group="identity-access" title="OIDC Claim Mapping" terms="claim path expected value role scope group service enabled"><p>Validated claim values grant existing CATS roles only within the selected scope. Unmatched values grant no OIDC role. Local assignments remain separate.</p><button type="button" className="button-secondary" onClick={() => {setMapping(null); setMappingOpen(true);}}>Add mapping</button><div className="table-wrap"><table><thead><tr>{['ID', 'Claim path', 'Expected value', 'Role', 'Scope', 'Status', 'Action'].map(title => <th key={title}>{title}</th>)}</tr></thead><tbody>{data.oidc_mappings?.length ? data.oidc_mappings.map((row: any) => <tr key={row.id}><td>{row.id}</td><td><code>{row.claim_path}</code></td><td>{row.expected_value}</td><td>{row.role?.name}</td><td>{row.global_scope ? 'Global' : row.service ? `Service: ${row.service.name}` : row.group ? `Group: ${row.group.name}` : 'Invalid'}</td><td>{row.enabled ? 'Enabled' : 'Disabled'}</td><td><button type="button" className="button-secondary" onClick={() => {setMapping(row); setMappingOpen(true);}}>Edit</button><Post data={data} action="/admin/configuration/oidc-mappings"><Hidden name="mapping_id" value={row.id}/><button name="action" value="delete">Delete</button></Post></td></tr>) : <tr><td colSpan={7}>No claim mappings configured.</td></tr>}</tbody></table></div><details className="config-edit-card" open={mappingOpen} onToggle={event => setMappingOpen(event.currentTarget.open)}><summary>Add or edit mapping</summary><Post key={mapping?.id || 'new'} data={data} action="/admin/configuration/oidc-mappings"><div className="config-grid"><label>Mapping ID<input name="mapping_id" type="number" min={0} defaultValue={mapping?.id || 0}/></label><TextFields values={mapping || {}} fields={ [['claim_path', 'Claim path', 'text', true], ['expected_value', 'Expected value', 'text', true]] }/><Choice name="role_id" label="CATS role" options={(data.oidc_roles || []).map((row: any) => [String(row.id), row.name])} value={mapping?.role_id}/><Choice name="scope" label="Scope" options={['global', 'group', 'service']} value={mapping ? mapping.global_scope ? 'global' : mapping.service_id ? 'service' : 'group' : 'global'}/><label>Scope ID (required for group or service scope)<input name="scope_id" type="number" min={0} defaultValue={mapping?.service_id || mapping?.group_id || 0}/></label><Check name="enabled" label="Enabled" checked={mapping ? mapping.enabled : true}/></div><button name="action" value="save">Save mapping</button></Post></details><p className="muted">Group IDs: {(data.oidc_groups || []).map((row: any) => `${row.id} ${row.name}`).join(', ') || 'none'}. Service IDs: {(data.oidc_services || []).map((row: any) => `${row.id} ${row.name}`).join(', ') || 'none'}.</p></Block>
  <Block group="security" title="Cybersecurity warning policy" terms="critical high KEV dependency watchlist POAM Kind missing evidence"><p>Selected conditions turn a compliant service yellow on the Cybersecurity page. CATS compliance policy continues to determine red.</p><Post data={data} action="/admin/configuration/cyber-warning-policy">{warningLabels.map(([key, label]) => <Check key={key} name="conditions" value={key} label={label} checked={data.cyber_warning_policy?.[key] !== false}/>)}<button>Save warning policy</button></Post></Block>
  <Block group="integrations" title="Deployment Validation Sandbox" terms="validator HTTPS endpoint client certificate private key CA mTLS connection"><p>Connect to a separate CATSchrödinger validator over mandatory mTLS. The client key is encrypted and never displayed after saving.</p>{data.validator_result && <p role="status">{data.validator_result}</p>}<p>Certificate: {validator.client_certificate_configured ? 'Configured' : 'Missing'} · Key: {validator.client_key_configured ? 'Configured' : 'Missing'} · CA: {validator.ca_configured ? 'Configured' : 'Missing'}</p><Post data={data} action="/admin/configuration/validator"><div className="config-grid"><TextFields values={{endpoint: validator.endpoint}} fields={ [['endpoint', 'Validator HTTPS endpoint', 'url'], ['client_certificate', 'Client certificate PEM (leave blank to keep)', 'textarea'], ['client_key', 'Client private key PEM (leave blank to keep)', 'textarea'], ['ca_certificate', 'Validator CA PEM (leave blank to keep)', 'textarea']] }/></div><button name="action" value="save">Save validator configuration</button><button name="action" value="test">Test Connection</button></Post></Block>
  <Block group="data" title="Security Data Sources" terms="CISA KEV EPSS Grype Trivy installed status source refresh upload offline database"><p>Updates are validated in staging; a failed candidate leaves installed data in place.</p><div className="settings-data-grid">{[['kev', 'CISA KEV'], ['epss', 'EPSS'], ['grype', 'Grype DB'], ['trivy', 'Trivy DB']].map(([key, title]) => {const row = data.security_data_sources?.[key] || {}, action = `/admin/configuration/security-data/${key}`; return <div className="config-edit-card" key={key}><h3>{title}</h3><p>Status: {row.status || 'NEVER_UPDATED'} · Installed: {row.installed_version || 'Unknown'} · Last attempt: {row.last_attempt_at || '—'} · Last success: {row.last_success_at || '—'}{row.failure_reason && <><br/>Failure: {row.failure_reason}</>}</p><Post data={data} action={action}><Hidden name="source" value={row.source}/><button name="action" value="refresh">Refresh</button></Post><details><summary>Configure and upload offline data</summary><Post data={data} action={action}><label>Configured source<input name="source" defaultValue={row.source || ''} placeholder={key === 'trivy' ? 'OCI database repository' : 'https://internal.example/data'}/></label><button name="action" value="save">Save source</button></Post>{key !== 'trivy' && <Post data={data} action={action} upload><input type="file" name="file" required aria-label={`${title} offline data`}/><button name="action" value="upload">Upload offline data</button></Post>}</details></div>;})}</div></Block>
  <Block group="integrations" title="OCI registries" terms="registry name endpoint repository project prefix purpose authentication username password token test staging"><p>Reusable registry endpoints for scan and patch jobs. Passwords/tokens are encrypted and never displayed after saving.</p><button type="button" className="button-secondary" onClick={() => {setRegistry(null); setRegistryOpen(true);}}>Add registry</button><div className="table-wrap"><table><thead><tr>{['Registry Name', 'Endpoint', 'Repository / Project Prefix', 'Purpose', 'Resolved Registry Path', 'Authentication', 'Status', 'Actions'].map(title => <th key={title}>{title}</th>)}</tr></thead><tbody>{(data.registries || []).map((row: any) => <tr key={row.id}><td>{row.display_name}</td><td className="breakable"><code>{row.endpoint}</code></td><td>{row.namespace || '—'}</td><td>{row.use_for_remediation ? 'Remediation staging' : 'General'}</td><td><code>{row.resolved_path}</code></td><td>{row.auth_mode === 'credentials' ? 'Credentials' : 'Anonymous'}{row.secret_configured && <small> (secret configured)</small>}</td><td>{row.status}<small>{row.status_detail}</small></td><td className="button-row"><button type="button" className="button-secondary" onClick={() => {setRegistry(row); setRegistryOpen(true);}}>Edit</button><Post data={data} action="/admin/configuration/registry-test"><Hidden name="registry_id" value={row.id}/><button className="button-secondary">Test</button></Post><Post data={data} action="/admin/configuration/registries"><Hidden name="registry_id" value={row.id}/><Hidden name="action" value="delete"/><button className="button-secondary">Delete</button></Post></td></tr>)}</tbody></table></div><details className="config-edit-card" open={registryOpen} onToggle={event => setRegistryOpen(event.currentTarget.open)}><summary>Add or update registry</summary><Post key={registry?.id || 'new'} data={data} action="/admin/configuration/registries"><div className="config-grid"><TextFields values={{...registry, registry_id: registry?.id}} fields={ [['display_name', 'Registry Name', 'text', true], ['endpoint', 'Endpoint', 'text', true], ['namespace', 'Repository / Project Prefix']] }/><Choice name="auth_mode" label="Authentication" options={ [['none', 'Anonymous'], ['credentials', 'Username and password/token']] } value={registry?.auth_mode || 'none'}/><TextFields values={{...registry, registry_id: registry?.id}} fields={ [['username', 'Username'], ['password', 'Password / token (leave blank to retain saved secret)', 'password'], ['registry_id', 'Registry ID (optional; existing ID updates)']] }/><Check name="use_for_remediation" label="Use as remediation staging registry" checked={registry?.use_for_remediation}/></div><button>Save registry</button></Post></details></Block>
  <Block group="integrations" title="Trusted CA certificates" terms="root intermediate PEM bundle fingerprint issuer subject trust upload remove"><p>Additional root and intermediate certificates extend the trust bundle for patching and repository clients. Certificates are identified by SHA-256 fingerprint.</p><Post data={data} action="/admin/configuration/trusted-certificates" upload className="trusted-ca-upload"><label>PEM certificate or bundle<input type="file" name="certificate" accept=".pem,.crt,.cer,application/x-pem-file" required/><small>Upload public CA certificates. Private keys are not accepted.</small></label><button>Add certificate(s)</button></Post>{data.certificates?.length ? <div className="trusted-ca-table"><table><thead><tr>{['Subject', 'Issuer', 'Type', 'Fingerprint', 'Actions'].map(title => <th key={title}>{title}</th>)}</tr></thead><tbody>{data.certificates.map((row: any) => <tr key={row.fingerprint}><td className="certificate-value" title={row.subject}>{row.subject}</td><td className="certificate-value" title={row.issuer}>{row.issuer}</td><td>{row.kind}</td><td className="certificate-fingerprint"><code title={row.fingerprint}>{row.fingerprint}</code></td><td><Post data={data} action="/admin/configuration/trusted-certificates"><Hidden name="remove_fingerprint" value={row.fingerprint}/><button className="button-secondary">Remove</button></Post></td></tr>)}</tbody></table></div> : <p><em>No additional certificates configured.</em></p>}</Block>
  <Block group="integrations" title="Operating-system repositories" terms="OS identifier package manager mode custom mirror repository URL TLS verification package signatures policy test delete"><p>One policy table covers built-in and custom operating systems. <strong>Image-defined</strong> uses repositories already declared by the image. Repository credentials are supplied only to an individual patch job and never stored here.</p>{data.repository_result && <p className="save-confirmation" role="status">{data.repository_result}</p>}<div className="table-wrap"><table><thead><tr>{['Operating system', 'OS ID', 'Package manager', 'Mode', 'Repository', 'TLS verification', 'Package signatures', 'Actions'].map(title => <th key={title}>{title}</th>)}</tr></thead><tbody>{Object.entries(data.os_definitions || {}).map(([key, raw]) => {const definition = raw as any, policy = data.repository_policies?.[key] || {}, isDefault = (policy.mode || 'default') === 'default'; return <tr key={key}><td>{definition.name}{data.custom_os?.includes(key) && <span className="muted"> (custom)</span>}</td><td><code>{key}</code></td><td>{definition.package_manager}</td><td>{isDefault ? 'Default' : 'Custom mirror'}</td><td className="breakable">{isDefault ? 'Image-defined' : policy.url || '—'}</td><td>{policy.verify_tls !== false ? 'On' : 'Off'}</td><td>{policy.verify_packages !== false ? 'On' : 'Off'}</td><td className="button-row"><a className="button-secondary" href={`/admin/configuration?edit_os_id=${encodeURIComponent(key)}`}>Edit</a><Post data={data} action="/admin/configuration/repository-test"><Hidden name="os_id" value={key}/><Hidden name="url" value={policy.url}/><button className="button-secondary">Test</button></Post>{data.custom_os?.includes(key) && <Post data={data} action="/admin/configuration/repositories"><Hidden name="action" value="delete"/><Hidden name="remove_os_id" value={key}/><button className="button-secondary">Delete</button></Post>}</td></tr>;})}</tbody></table></div>{data.edit_os_id && data.os_definitions?.[data.edit_os_id] && <div className="config-edit-card"><h3>Edit {data.os_definitions[data.edit_os_id].name}</h3><RepositoryForm key={data.edit_os_id} data={data} id={data.edit_os_id} definition={data.os_definitions[data.edit_os_id]} policy={data.repository_policies?.[data.edit_os_id]}/></div>}<details className="config-edit-card"><summary>Add operating system</summary><RepositoryForm data={data}/></details></Block>
  </>}
  </section></div></SettingsContext.Provider>;
}
