import {can, type PageData} from '../api';
import {Csrf, safeReference} from '../components/Form';

export function Page({data}: {data: PageData}) {
  const {service, finding, evidence, risk} = data;
  const root = `/services/${encodeURIComponent(service.service_key)}`;
  const references: string[] = evidence.urls || [];
  return <><a className="back" href={root}>← {service.name}</a><section className="heading"><div><p className="eyebrow">ADVISORY DETAIL</p><h1>{finding.cve}</h1><p>{service.name} · {evidence.namespace || 'Unknown namespace'}</p></div><div><span className={`status large ${finding.active ? 'bad' : 'ok'}`}>{finding.active ? 'Active' : 'Resolved'}</span>{data.remediation_enabled && finding.active && can(data, 'remediation.execute', service.id) && <form method="post" action={`${root}/findings/${finding.id}/remediate`}><Csrf data={data}/><button>Remediate</button></form>}</div></section>
    <section className="panel"><div className="panel-head"><div><h2>Remediation classification</h2><p>{data.remediation_classification.reason}</p></div><span className="status">{data.remediation_classification.classification}</span></div></section>
    <section className="metrics">{[['Severity', finding.severity], ['KEV', risk.kev ? 'Yes' : 'No'], ['EPSS', Number(risk.epss || 0).toFixed(2)], ['Current age', data.age == null ? '—' : `${data.age} days`], ['First seen', finding.first_seen], ['Due date', data.due_date || '—'], ['Recurrences', finding.recurrence_count]].map(([label, value]) => <article key={label}><span>{label}</span><strong>{value}</strong></article>)}</section>
    <section className="detail-grid"><article className="panel detail-panel"><h2>Description</h2><p>{evidence.description || 'No description was supplied by the scanner.'}</p><dl><dt>Data source</dt><dd>{evidence.data_source ? <a href={safeReference(evidence.data_source)}>{evidence.data_source}</a> : '—'}</dd><dt>Package type</dt><dd>{evidence.package_type || '—'}</dd><dt>Last seen</dt><dd>{finding.last_seen}</dd><dt>Exception</dt><dd>{data.exception ? `Accepted until ${data.exception.expires_at} by ${data.exception.approved_by}` : 'None'}</dd></dl></article><article className="panel detail-panel"><h2>CVSS</h2>{evidence.cvss?.length ? evidence.cvss.map((score: any, index: number) => <div className="cvss-entry" key={index}><strong>{score.baseScore ?? '—'}</strong><code>{score.vector || 'No vector'}</code></div>) : <p>No CVSS data was supplied.</p>}<h2>References</h2><ul className="reference-list">{references.length ? references.map((url, index) => <li key={index}><a href={safeReference(url)}>{url}</a></li>) : <li>No references supplied.</li>}</ul></article></section>
    <section className="panel"><div className="panel-head"><div><h2>Currently affected</h2><p>Image and package evidence from the latest complete assessment.</p></div></div><div className="table-wrap"><table><thead><tr>{['Image', 'Package', 'Installed', 'Fixed versions'].map(label => <th key={label}>{label}</th>)}</tr></thead><tbody>{data.current_observations.length ? data.current_observations.map((item: any, index: number) => <tr key={index}><td><code>{item.image}</code></td><td>{item.package || '—'}</td><td>{item.installed_version || '—'}</td><td>{item.fixed_version || '—'}</td></tr>) : <tr><td colSpan={4} className="empty">No current affected image.</td></tr>}</tbody></table></div></section></>;
}

export function Watchlist({data}: {data: PageData}) {
  const {match, service} = data;
  return <><section className="heading"><div><p className="eyebrow">WARNING EVIDENCE</p><h1>{match.component_name}</h1><p>Configured Dependency Watchlist match in {service.name}. This warning does not change compliance status.</p></div></section><section className="panel padded"><dl className="detail-grid-list">{[['Component', match.component_name], ['Version', match.component_version], ['Ecosystem', match.ecosystem], ['PURL', match.component_purl], ['Image', match.image], ['SBOM scan', `${match.execution_key} · ${match.scanned_at}`], ['Watchlist entry', `${match.entry.purl || match.entry.name} ${match.entry.version_constraint || ''}`]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value || '—'}</dd></div>)}</dl><p><a href={`/services/${encodeURIComponent(service.service_key)}?finding_state=warnings`}>Back to warnings</a></p></section></>;
}
