import {useRef,useState} from 'react';
import type {PageData} from '../api';
interface Column {field:string;heading:string;enabled:boolean}
interface DesignerData extends PageData {kind:string;name:string;source:string;mode:string;group_id?:number|null;saved?:boolean;columns:Column[];labels:Record<string,string>;defaults:Record<string,string>}
function Designer({data:raw}:{data:PageData}) {
  const data=raw as DesignerData; const [columns,setColumns]=useState(()=>data.columns.map(c=>({...c}))); const buttons=useRef(new Map<string,HTMLButtonElement>()); const group=data.group_id||'';
  const root=`/admin/general-policy/export-templates/${encodeURIComponent(data.kind)}`; const query=`?group_id=${encodeURIComponent(group)}`;
  const change=(field:string,update:Partial<Column>)=>setColumns(previous=>previous.map(row=>row.field===field?{...row,...update}:row));
  const move=(index:number,offset:number)=>{const next=index+offset;if(next<0||next>=columns.length)return;const result=[...columns];[result[index],result[next]]=[result[next],result[index]];setColumns(result);queueMicrotask(()=>buttons.current.get(`${columns[index].field}:${offset}`)?.focus());};
  return <><a className="back" href={`/admin/general-policy${query}`}>← General Policy</a><section className="heading"><div><p className="eyebrow">EXPORT TEMPLATES</p><h1>{data.name}</h1><p>Choose columns, set their Excel headings, and use the order controls to arrange them. Changes affect future downloads.</p></div></section><section className="panel padded purpose-template-editor">{data.saved&&<p role="status" className="save-confirmation">Template saved.</p>}<p>Policy: <strong>{data.mode[0].toUpperCase()+data.mode.slice(1)}</strong> · Effective template: <strong>{data.source}</strong></p><form method="post" action={`${root}${query}`}><input type="hidden" name="csrf_token" value={data.csrf_token||''}/><div className="table-wrap"><table><thead><tr>{['Include','Field','Excel Heading','Order'].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{columns.map((column,i)=><tr key={column.field}><td><label><input type="checkbox" name="enabled" value={column.field} checked={column.enabled} onChange={e=>change(column.field,{enabled:e.target.checked})}/><span className="sr-only">Include {data.labels[column.field]}</span></label></td><td>{data.labels[column.field]}<input type="hidden" name="field" value={column.field}/></td><td><label><span className="sr-only">Excel heading for {data.labels[column.field]}</span><input name="heading" maxLength={120} required value={column.heading} onChange={e=>change(column.field,{heading:e.target.value})}/></label><button type="button" className="button-secondary default-heading" onClick={()=>change(column.field,{heading:data.defaults[column.field]})}>Default heading</button></td><td>{[[-1,'up','↑'],[1,'down','↓']].map(([offset,direction,label])=><button key={direction} ref={element=>{if(element)buttons.current.set(`${column.field}:${offset}`,element);}} type="button" className="button-secondary" aria-label={`Move ${data.labels[column.field]} ${direction}`} onClick={()=>move(i,Number(offset))}>{label}</button>)}</td></tr>)}</tbody></table></div><div className="config-actions"><button type="submit">Save custom template{group?' for this group':''}</button></div></form><form method="post" action={`${root}/reset${query}`} className="purpose-template-reset"><input type="hidden" name="csrf_token" value={data.csrf_token||''}/>{group?<><button type="submit" name="mode" value="inherit" className="button-secondary">Inherit parent</button> <button type="submit" name="mode" value="default" className="button-secondary">Use CATS Default</button></>:<button type="submit" className="button-secondary">Restore built-in defaults</button>}</form></section></>;
}
export function Page({data}:{data:PageData}) {return <Designer key={JSON.stringify([data.kind,data.group_id,data.columns])} data={data}/>;}
