import {useEffect, useRef, useState, type ReactNode} from 'react';
import {can, requestJson, type PageData} from '../api';
import {ServiceHeader, ServiceTabs} from '../components/ServiceHeader';
import {Callout, ExpandableEvidence, MetricCard, StatusBadge, humanize} from '../components/ui';

/** Ready / expected runtime counts. A missing measurement is never shown as zero. */
function runtimeCount(entry: any) {
  const ready = entry?.ready, expected = entry?.expected;
  if (ready == null && expected == null) return <span className="metric-value-missing" title="The validation did not report this measurement">Not reported</span>;
  return <>{ready ?? '?'} / {expected ?? '?'}</>;
}
const reported = (value: any) => value == null ? <span className="metric-value-missing" title="The validation did not report this measurement">Not reported</span> : value;

function Table({title, columns, rows, render, paginate = false, empty = 'Not provided'}: {title: string; columns: string[]; rows: any[]; render: (row: any, index: number) => ReactNode; paginate?: boolean; empty?: string}) {
  const [page, setPage] = useState(1);
  const total = Math.max(1, Math.ceil(rows.length / 10));
  const current = Math.min(page, total);
  const visible = paginate ? rows.slice((current - 1) * 10, current * 10) : rows;
  return <article className="overview-dashboard-card"><h3>{title}{rows.length > 0 && <span className="count-pill">{rows.length}</span>}</h3>{rows.length ? <><div className="overview-table-wrap"><table className="overview-table"><thead><tr>{columns.map(column => <th key={column}>{column}</th>)}</tr></thead><tbody>{visible.map((row, index) => <tr key={index}>{render(row, index)}</tr>)}</tbody></table></div>{paginate && total > 1 && <nav className="overview-pagination pagination" aria-label={`${title} pages`}><span>Showing {(current - 1) * 10 + 1}–{Math.min(current * 10, rows.length)} of {rows.length}</span><span className="overview-pagination-controls"><button type="button" className="secondary-button" disabled={current === 1} onClick={() => setPage(current - 1)}>Previous</button><span>Page {current} of {total}</span><button type="button" className="secondary-button" disabled={current === total} onClick={() => setPage(current + 1)}>Next</button></span></nav>}</> : <p className="overview-empty">{empty}</p>}</article>;
}

export function Page({data}: {data: PageData}) {
  const service = data.view.service;
  const root = `/services/${encodeURIComponent(service.service_key)}`;
  const overview = data.overview_data || {};
  const selectedVersion = data.view_version || new URLSearchParams(window.location.search).get('view_version') || '';
  const evidenceUrl = `/api/v1/services/${encodeURIComponent(service.service_key)}/architecture-evidence${selectedVersion ? `?view_version=${encodeURIComponent(selectedVersion)}` : ''}`;
  const [architecture, setArchitecture] = useState(data.architecture_verification || {});
  const [summary, setSummary] = useState(data.architecture_graph?.summary || {});
  const [action, setAction] = useState<{kind: string; row: any} | null>(null);
  const dialog = useRef<HTMLDialogElement>(null);
  useEffect(() => {if (action) dialog.current?.showModal();}, [action]);
  // Poll only while a Deployment Validation is running; stop at a terminal state.
  const [polling, setPolling] = useState(Boolean(data.architecture_polling));
  useEffect(() => {
    if (!polling) return;
    let stopped = false;
    const controller = new AbortController();
    let timer: ReturnType<typeof setTimeout>;
    const summaryUrl = `${evidenceUrl}${evidenceUrl.includes('?') ? '&' : '?'}summary=true`;
    const poll = async () => {
      if (!document.hidden) {
        try {const result = await requestJson<any>(summaryUrl, {signal: controller.signal});
          if (!stopped) {
            setArchitecture(result.architecture || {}); setSummary(result.graph?.summary || {});
            if (!result.active_validation) {stopped = true; setPolling(false); return;}
          }
        } catch { /* Keep the persisted evidence summary visible. */ }
      }
      if (!stopped) timer = setTimeout(poll, 5000);
    };
    timer = setTimeout(poll, 5000);
    return () => {stopped = true; controller.abort(); clearTimeout(timer);};
  }, [evidenceUrl, polling]);
  const csrf = <input type="hidden" name="csrf_token" value={data.csrf_token || ''}/>;
  const removeEvidence = can(data, 'evidence.remove', service.id);
  const archiveAllowed = can(data, 'archive.request', service.id);
  const validation = data.deployment_validation || {};
  const validationStatus = ['VERIFIED', 'PARTIALLY_VERIFIED', 'COULD_NOT_VALIDATE', 'NOT_ATTEMPTED'].includes(validation.status) ? validation.status : validation.status ? 'IN_PROGRESS' : 'NOT_ATTEMPTED';
  const resources = validation.resource_summary || {};
  const chartGraph = data.chart_graph || {};
  const close = () => {dialog.current?.close(); setAction(null);};
  return <><ServiceHeader data={data}/><ServiceTabs serviceKey={service.service_key} active="overview"/>
    {data.evidence_notice === 'stale' && <p className="error callout callout-danger" role="alert">The evidence changed since this page was opened. Refresh and review the current evidence before removing it.</p>}
    {data.artifact_provenance?.length > 0 && <section className="panel known-artifacts" aria-label="Known Artifacts"><div className="panel-head"><div><h2>Known Artifacts</h2><p>These artifacts match CATS remediation outputs by immutable digest. Evidence below describes the producing candidate; matching artifacts do not establish verification or lineage for the complete release.</p></div></div><Table title="Artifact provenance" columns={['Artifact', 'Produced by', 'Immutable digest', 'Post-remediation scan', 'Runtime verification', 'Signature']} rows={data.artifact_provenance} paginate render={row => <><td>{row.artifact_kind === 'helm' ? 'Helm chart' : 'Image'}<small className="muted"> · {row.identity_type === 'package_sha256' ? 'Package SHA-256' : 'OCI manifest'}</small></td><td>Service {row.source_version || 'Unknown version'} / Remediation {row.revision_number ? `R${row.revision_number}` : row.job_key || 'Unknown revision'}</td><td><code>{row.digest}</code></td><td><StatusBadge value={row.post_remediation_scan || 'NOT_RUN'}/></td><td><StatusBadge value={row.runtime_verification || 'NOT_VERIFIED'}/></td><td><StatusBadge value={row.signature || 'NOT_REQUESTED'}/></td></>}/></section>}
    <nav className="metric-grid metric-filters" aria-label="Filter service findings">{[['active', 'Active Fixable', undefined], ['noncompliant', 'Active Non-Compliance', 'danger'], ['exceptions', 'Active Exceptions', undefined], ['resolved', 'Resolved', undefined], ['warnings', 'Warnings', 'warning']].map(([key, label, tone]) => <MetricCard key={key} label={label} value={data.finding_counts?.[key as string] || 0} tone={tone && data.finding_counts?.[key as string] > 0 ? tone as any : undefined} href={`${root}?overview=false&finding_state=${key}&finding_type=all&page_size=50`}/>)}</nav>
    <div className="overview-status-grid">
    <article className="overview-dashboard-card architecture-summary-card"><div className="deployment-validation-card-head"><div><h3>Architecture</h3><p>Declared and persisted runtime evidence remain independent from static findings.</p></div><StatusBadge value={architecture.state || 'N/A'} label={architecture.label || 'N/A'}/></div><div className="validation-metrics">{[['Declared resources', summary.declared ?? architecture.expected ?? 0], ['Runtime verified', architecture.observed || 0], ['Unverified / differences', architecture.missing || summary.differences || 0], ['Relationships', summary.relationships || 0], ['Unresolved relationships', summary.unresolved || 0]].map(([label, value]) => <span key={label}><small>{label}</small><strong>{value}</strong></span>)}</div><div className="validation-actions"><a className="secondary-button" href={`${root}?architecture=true`}>View Architecture</a>{architecture.state === 'PARTIALLY_VERIFIED' && <a className="secondary-button" href={`${root}?architecture=true#differences`}>Review Differences</a>}</div></article>
    <article className="overview-dashboard-card deployment-validation-card"><div className="deployment-validation-card-head"><div><h3>Deployment Validation</h3><p>Validation engine: <strong>{validation.diagnostics?.schrodinger ? 'CATSchrödinger’s' : validation.engine || 'kind'}</strong>{validation.artifact_reference && <> · Helm evidence: <code>{validation.artifact_reference}</code></>}</p></div></div>
      <dl className="evidence-kinds"><div><dt>Static scan</dt><dd><StatusBadge value={validation.static_scan_complete ? 'complete' : validation.static_scan_complete === false ? 'incomplete' : 'not_linked'} label={validation.static_scan_complete ? 'Complete' : validation.static_scan_complete === false ? 'Incomplete' : 'Not linked'} tone={validation.static_scan_complete ? 'success' : validation.static_scan_complete === false ? 'warning' : 'neutral'}/></dd></div><div><dt>Runtime validation</dt><dd><StatusBadge value={validationStatus} label={humanize(validationStatus)} tone={validationStatus === 'IN_PROGRESS' ? 'info' : undefined}/></dd></div></dl>
      <p className="deployment-validation-explanation">{validation.reason || 'Validation has not been requested for a Helm artifact.'}</p><div className="validation-metrics">{[['Pods', 'pods'], ['Deployments', 'deployments'], ['StatefulSets', 'statefulsets']].map(([label, key]) => <span key={key}><small>{label}</small><strong>{runtimeCount(resources[key])}</strong></span>)}<span><small>Helm install</small><strong>{validation.helm_result?.install ? <StatusBadge value={validation.helm_result.install}/> : <StatusBadge value="NOT_ATTEMPTED"/>}</strong></span><span><small>CrashLoopBackOff</small><strong>{reported(validation.conditions?.crashloopbackoff)}</strong></span><span><small>ImagePullBackOff</small><strong>{reported(validation.conditions?.imagepullbackoff)}</strong></span><span><small>Validation time</small><strong>{typeof validation.duration_seconds === 'number' ? `${validation.duration_seconds}s` : '—'}</strong></span></div><div className="validation-actions"><a className="secondary-button" href={`${root}?validation=true`}>View Validation</a>{validation.has_observed_topology && <a className="secondary-button" href={`${root}?validation=true#observed-topology`}>View Observed Topology</a>}</div></article>
    </div>
    <section className="normalized-overview" aria-labelledby="overview-title"><div className="section-title-row"><h2 id="overview-title">Declared configuration</h2><p className="overview-provenance">Source: {overview.source}{validation.execution_key && <> · Helm evidence execution: <code>{validation.execution_key}</code></>} · Runtime-observed traffic is not inferred.</p></div>{overview.description && <p className="overview-description">{overview.description}</p>}{overview.warnings?.length > 0 && <Callout tone="warning" title="Static-analysis warning" className="overview-render-warning">{overview.warnings.map((warning: any, index: number) => <div key={index}><p>{warning.message}{warning.chart && <> Chart: <code>{warning.chart}</code>.</>}{warning.source && warning.source !== '—' && <> Source: <code>{warning.source}</code>.</>}{warning.unrecognized_images?.length > 0 && <> Unrecognized image(s): {warning.unrecognized_images.join(', ')}</>}</p>{warning.original_error && <details><summary>Helm diagnostic</summary><code>{warning.original_error}</code></details>}</div>)}</Callout>}
      <div className="overview-top-row"><Table title="Missing Evidence" columns={['Type', 'Item', 'Why It’s Missing', 'Source File', ...(removeEvidence ? ['Action'] : [])]} rows={overview.missing_evidence || []} paginate empty="No missing evidence." render={row => <><td>{row.type}</td><td>{row.item}</td><td>{row.reason}</td><td><code>{row.source_file || '—'}</code></td>{removeEvidence && <td>{row.removable && <button type="button" className="link-button" onClick={() => setAction({kind: 'evidence', row})}>Remove</button>}</td>}</>}/><Table title="Ports & Protocols" columns={['Port', 'Protocol', 'Service', 'Declared By']} rows={overview.ports || []} paginate render={row => <><td>{row.port}</td><td>{row.protocol}</td><td>{row.service}</td><td title={row.provenance}>{row.declared_by}</td></>}/><Table title="Accounts" columns={['Name', 'Scope', 'Relationships']} rows={overview.accounts || []} paginate render={row => <><td>{row.name}</td><td>{row.scope}</td><td>{row.relationships && row.relationships !== '—' ? <ul className="overview-relationship-list">{row.relationships.split(';').map((relationship: string, index: number) => <li key={index}>{relationship}</li>)}</ul> : '—'}</td></>}/></div>
      <Table title="Discovered Artifacts" columns={['Type', 'Registry', 'Repository', 'Artifact', 'Version / Tag', 'Discovered From', 'Digest']} rows={overview.artifacts || []} paginate render={row => <>{['type', 'registry', 'repository', 'artifact', 'version', 'discovered_from'].map(key => <td key={key}>{row[key] || '—'}</td>)}<td>{row.digest ? <code className="truncate" title={row.digest}>{row.digest}</code> : '—'}</td></>}/>
      {data.service_images?.length > 0 && <Table title="Container Images" columns={['Image', 'Digest', 'Lifecycle', 'Actions']} rows={data.service_images} paginate render={row => <><td><code className="image-ref">{row.image_reference}</code></td><td><code>{row.image_digest || '—'}</code></td><td><StatusBadge value={row.lifecycle_status}/>{row.replacement_of_id && <small>Replaced image lineage recorded</small>}</td><td>{row.lifecycle_status === 'active' && archiveAllowed ? <span className="row-actions"><button type="button" className="secondary-button" onClick={() => setAction({kind: 'remove', row})}>Request Removal</button><button type="button" className="secondary-button" onClick={() => setAction({kind: 'replace', row})}>Replace With</button></span> : '—'}</td></>}/>}</section>
    {(chartGraph.charts?.length > 0 || chartGraph.unresolved?.length > 0) && <ExpandableEvidence className="helm-chart-discovery" summary={<>Helm charts discovered: {chartGraph.charts?.length || 0}{chartGraph.unresolved?.length > 0 && <> · {chartGraph.unresolved.length} unresolved references</>}</>}><Table title="Chart discovery" columns={['Chart', 'Instance', 'Version', 'Parent', 'Discovery', 'Source', 'Status', 'Resources', 'Images', 'Diagnostic']} rows={(chartGraph.charts || []).filter((chart: any) => !chart.source_only)} render={chart => <><td>{chart.chart}</td><td>{chart.instance || '—'}</td><td>{chart.version || '—'}</td><td>{chart.parent_chart_name || chart.parent || 'Root'}</td><td>{chart.discovery_method || '—'}</td><td><code>{chart.discovery_source_file || chart.source || '—'}{chart.yaml_path && ` → ${chart.yaml_path}`}</code></td><td>{chart.status || chart.resolution || '—'}</td><td>{chart.resource_count ?? '—'}</td><td>{chart.image_count ?? '—'}</td><td>{chart.render_error || chart.error || '—'}</td></>}/>{chartGraph.unresolved?.length > 0 && <><h3>Unresolved chart references</h3><ul>{chartGraph.unresolved.map((item: any, index: number) => <li key={index}><strong>{item.item}</strong> — {item.reason}{item.source_file && <code>{item.source_file}{item.yaml_path && `#${item.yaml_path}`}</code>}</li>)}</ul></>}</ExpandableEvidence>}
    <dialog ref={dialog} className="review-dialog" onCancel={() => setAction(null)}>{action && <form method="post" action={action.kind === 'evidence' ? `${root}/missing-evidence/remove` : `${root}/images/${action.row.id}/${action.kind}`}>{csrf}<h3>{action.kind === 'evidence' ? 'Remove missing evidence?' : action.kind === 'replace' ? 'Replace image' : 'Request image removal'}</h3>{action.kind === 'evidence' ? <><input type="hidden" name="execution_id" value={data.latest_execution?.id || ''}/><input type="hidden" name="evidence_type" value={action.row.type}/><input type="hidden" name="item" value={action.row.item}/><input type="hidden" name="source_file" value={action.row.source_file || ''}/><p>{action.row.type} · {action.row.item} will be removed from the current service state. It will reappear if a future assessment reports it again.</p></> : <><p><code>{action.row.image_reference}</code></p>{action.kind === 'replace' && <label>Replacement image<input name="replacement_reference" required placeholder="registry.example/app:2.4"/></label>}<label>Reason or comment<textarea name="reason" minLength={3} required/></label></>}<div className="dialog-actions"><button type="button" className="secondary-button" onClick={close}>Cancel</button><button className={action.kind === 'evidence' ? 'danger-button' : undefined}>{action.kind === 'evidence' ? 'Remove' : 'Submit request'}</button></div></form>}</dialog>
  </>;
}
