import {useCallback,useEffect,useRef,useState} from 'react';
import {requestJson,type PageData} from '../api';
import {ServiceTabs} from '../components/ServiceHeader';

const layers = [['all','All Resources'],['declared','Declared'],['runtime','Runtime Observed'],['differences','Differences'],['configuration','Configuration'],['containers','Containers'],['flow','Data Flow'],['network','Network'],['storage','Storage']];
export function Page({data}:{data:PageData}) {
  const service=data.view.service, root=`/services/${encodeURIComponent(service.service_key)}`;
  const selectedVersion=data.view_version || new URLSearchParams(window.location.search).get('view_version') || new URLSearchParams(window.location.search).get('version') || '';
  const evidenceUrl=`/api/v1/services/${encodeURIComponent(service.service_key)}/architecture-evidence${selectedVersion?`?view_version=${encodeURIComponent(selectedVersion)}`:''}`;
  const [graph,setGraph]=useState(data.architecture_graph || {}), [verification,setVerification]=useState(data.architecture_verification || {});
  const [layer,setLayer]=useState('all'), [selection,setSelection]=useState<any>(null), [camera,setCamera]=useState({x:0,y:0,scale:1});
  const [size,setSize]=useState({width:1200,height:620}),[error,setError]=useState('');
  const svg=useRef<SVGSVGElement>(null),drag=useRef<any>(null);
  const layout=graph.layouts?.[layer] || graph.layouts?.all || graph.layouts?.flow;
  const nodes=new Map<string,any>((graph.nodes || []).map((node:any)=>[node.id,node]));
  const fit=useCallback(()=>setCamera({scale:1,x:Math.max(0,(size.width-(layout?.bounds?.width || 0))/2)-(layout?.bounds?.x || 0),y:Math.max(0,(size.height-(layout?.bounds?.height || 0))/2)-(layout?.bounds?.y || 0)}),[layout,size.width,size.height]);
  useEffect(()=>{fit();},[fit]);
  useEffect(()=>{
    let cancelled=false,timer:ReturnType<typeof setTimeout>; const controller=new AbortController();
    const poll=async()=>{try {if(!document.hidden){const state=await requestJson<any>(evidenceUrl,{signal:controller.signal});if(!cancelled){setVerification(state.architecture || {});if(state.graph){setGraph((old:any)=>JSON.stringify(old)===JSON.stringify(state.graph)?old:state.graph);setLayer(old=>state.graph.layouts?.[old]?old:'all');setSelection((old:any)=>old && [...(state.graph.nodes || []),...(state.graph.relationships || [])].find(item=>item.id===old.id) || null);}}}}catch {/* Keep the last verified evidence during temporary outages. */}finally{if(!cancelled)timer=setTimeout(poll,5000);}};
    timer=setTimeout(poll,5000);return()=>{cancelled=true;clearTimeout(timer);controller.abort();};
  },[evidenceUrl]);
  useEffect(()=>{
    if(!svg.current || typeof ResizeObserver==='undefined')return;
    let timer:ReturnType<typeof setTimeout>,width=0,sequence=0,controller:AbortController|undefined;
    const observer=new ResizeObserver(()=>{clearTimeout(timer);timer=setTimeout(async()=>{const box=svg.current?.getBoundingClientRect();if(!box?.width)return;setSize({width:box.width,height:box.height || 620});const next=Math.max(240,Math.min(10000,Math.floor(box.width/16)*16));if(next===width)return;width=next;controller?.abort();controller=new AbortController();const current=++sequence;try{const url=new URL(window.location.href);url.searchParams.set('architecture','true');if(selectedVersion)url.searchParams.set('view_version',selectedVersion);url.searchParams.set('layout_width',String(next));const layouts=await requestJson<any>(url.pathname+url.search,{signal:controller.signal});if(current===sequence){setGraph((old:any)=>({...old,layouts}));setError('');}}catch{if(current===sequence && !controller.signal.aborted){width=0;setError('Could not refresh the layout. Resize or reload to retry.');}}},180);});
    observer.observe(svg.current);return()=>{sequence++;clearTimeout(timer);controller?.abort();observer.disconnect();};
  },[selectedVersion]);
  const zoom=(delta:number,x=size.width/2,y=size.height/2)=>setCamera(old=>{const scale=Math.max(.25,Math.min(3,old.scale+delta));return {scale,x:x-(x-old.x)*scale/old.scale,y:y-(y-old.y)*scale/old.scale};});
  const related=new Set<string>();if(selection){related.add(selection.id);for(const edge of graph.relationships || [])if(edge.id===selection.id || edge.source===selection.id || edge.target===selection.id){related.add(edge.id);related.add(edge.source);related.add(edge.target);}}
  const select=(item:any)=>setSelection(item);
  const keySelect=(event:React.KeyboardEvent,item:any)=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();select(item);}};
  const state=data.architecture_state;
  return <><a className="back" href={`${root}?overview=true`}>← Service overview</a><section className="heading"><div><p className="eyebrow">{service.service_key}</p><h1>{service.name} Architecture</h1><p>Normalized relationships from the latest rendered Helm / Kubernetes evidence.</p><p>Latest Evidence: {data.view.last_execution || 'None received'}</p></div><details className="architecture-verification"><summary className={`status ${verification.state==='VERIFIED'?'ok':'warning'}`}>{verification.state==='VERIFIED'?'✓ ':''}{verification.label || 'N/A'}</summary>{['VERIFIED','PARTIALLY_VERIFIED'].includes(verification.state)?<p>Observed {verification.observed} / {verification.expected}; Missing {verification.missing}; Failed {verification.failed}<br />{verification.completed_at} · {verification.engine}</p>:<p>{verification.reason}</p>}{verification.run_key?<a href={`${root}?validation=true&run=${encodeURIComponent(verification.run_key)}`}>View Deployment Validation</a>:verification.state==='DECLARED'&&<a href={`${root}?validation=true`}>Run Deployment Validation</a>}</details></section><ServiceTabs serviceKey={service.service_key} active="architecture" />
    {state==='NO_SOURCE'?<section className="empty"><h2>No architecture source available</h2><p>Add Helm charts or Kubernetes manifests to build the architecture.</p><a href={`${root}?artifacts=true`}>Manage artifacts</a></section>:state==='ANALYSIS_INCOMPLETE'?<section className="empty"><h2>Architecture analysis incomplete</h2><a href={`/scan?service=${encodeURIComponent(service.service_key)}`}>Run a scan</a></section>:<>
    {state==='NO_RELATIONSHIPS'&&<p className="notice">No relationships could be established from supplied evidence.</p>}{graph.incomplete&&<p className="notice warning">Architecture evidence is incomplete. Review warnings and unresolved resources below.</p>}
    <section className="architecture-panel"><div className="architecture-toolbar"><label>Layer <select value={layer} onChange={event=>{setLayer(event.target.value);setSelection(null);}}>{layers.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><span>Declared · Runtime Observed · Inferred</span><div className="architecture-controls" style={{position:'static'}}><button onClick={()=>zoom(-.25)} aria-label="Zoom out">−</button><output>{Math.round(camera.scale*100)}%</output><button onClick={()=>zoom(.25)} aria-label="Zoom in">+</button><button onClick={()=>setCamera({x:0,y:0,scale:1})}>Reset</button><button onClick={fit}>Fit</button></div></div>{error&&<p role="status">{error}</p>}
    <div className="architecture-layout"><svg ref={svg} className={`architecture-svg${drag.current?' is-panning':''}`} viewBox={`0 0 ${size.width} ${size.height}`} aria-label="Service architecture graph" onWheel={event=>{event.preventDefault();const box=event.currentTarget.getBoundingClientRect();zoom(event.deltaY<0?.15:-.15,(event.clientX-box.left)*size.width/(box.width || size.width),(event.clientY-box.top)*size.height/(box.height || size.height));}} onPointerDown={event=>{if((event.target as Element).closest('[data-graph-item]'))return;drag.current={x:event.clientX,y:event.clientY};event.currentTarget.setPointerCapture?.(event.pointerId);}} onPointerMove={event=>{if(!drag.current)return;const delta={x:event.clientX-drag.current.x,y:event.clientY-drag.current.y};drag.current={x:event.clientX,y:event.clientY};setCamera(old=>({...old,x:old.x+delta.x,y:old.y+delta.y}));}} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}><defs><marker id="architecture-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="context-stroke" /></marker></defs><g transform={`translate(${camera.x} ${camera.y}) scale(${camera.scale})`}>
    {(layout?.edges || []).map((edge:any)=>{const item=(graph.relationships || []).find((value:any)=>value.id===edge.id) || edge;return <g key={edge.id} data-graph-item="edge" role="button" tabIndex={0} aria-label={`Relationship ${item.label}`} onClick={()=>select(item)} onKeyDown={event=>keySelect(event,item)} className={selection&&!related.has(edge.id)?'is-dim':''}><path className={`architecture-edge ${String(item.classification || 'derived').toLowerCase()}`} d={(edge.points || []).map((point:any,index:number)=>`${index?'L':'M'} ${point.x} ${point.y}`).join(' ')} markerEnd="url(#architecture-arrow)" /><text className="architecture-edge-label" x={edge.label_position?.x} y={edge.label_position?.y}>{(edge.label_lines || [item.label]).map((line:string,index:number)=><tspan key={index} x={edge.label_position?.x} dy={index?14:0}>{line}</tspan>)}</text></g>;})}
    {(layout?.node_ids || []).map((id:string)=>{const item=nodes.get(id),point=layout.positions?.[id];if(!item || !point)return null;return <g key={id} data-graph-item="node" role="button" tabIndex={0} aria-label={item.label || item.name} onClick={()=>select(item)} onKeyDown={event=>keySelect(event,item)} className={`architecture-node ${String(item.provenance || 'DECLARED').toLowerCase().replaceAll('_','-')}${selection&&!related.has(id)?' is-dim':''}`} transform={`translate(${point.x-92} ${point.y-28})`}><title>{item.kind} · {item.name} · {item.namespace}</title><rect width="184" height="56" rx="8" /><text x="12" y="20">{item.kind || item.type}</text><text x="12" y="40">{String(item.name || item.label).slice(0,25)}</text></g>;})}</g></svg>
    {selection&&<aside className="architecture-details" aria-label="Selection details"><button aria-label="Close selection" onClick={()=>setSelection(null)}>×</button><h2>{selection.label || selection.id}</h2><dl>{[['ID',selection.id],['Classification',(selection.classifications || [selection.classification || selection.kind]).join(' + ')],['Source',nodes.get(selection.source)?.label || selection.source],['Destination',nodes.get(selection.target)?.label || selection.target],['Provenance',selection.provenance || 'DECLARED'],['Confidence',selection.confidence]].filter(([,value])=>value).map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>{selection.network?.ports?.map((port:any,index:number)=><p key={index}>{port.servicePort} → {port.targetPort} / {port.protocol}</p>)}{selection.chart_provenance&&<><h3>Chart provenance</h3><dl>{Object.entries(selection.chart_provenance).filter(([,value])=>typeof value==='string'||typeof value==='number').map(([key,value])=><div key={key}><dt>{key.replaceAll('_',' ')}</dt><dd>{String(value)}</dd></div>)}</dl></>}{(selection.evidence || []).map((item:any,index:number)=><p key={index}>{item.detail}<br />{item.source}</p>)}</aside>}</div></section>
    <section className="architecture-metrics">{['nodes','relationships','unresolved','warnings','ports'].map(key=><span key={key}>{key}: <strong>{graph.summary?.[key] || 0}</strong> </span>)}</section><section><h2>Evidence warnings</h2>{(graph.warnings || []).length?(graph.warnings || []).map((item:any,index:number)=><p key={index}>{typeof item==='string'?item:[item.item,item.reason || item.message].filter(Boolean).join(': ')}</p>):<p>No warnings.</p>}<h2>Unresolved resources</h2>{(graph.unresolved || []).map((item:any,index:number)=><p key={index}>{item.node_id}: {item.reason}</p>)}</section></>}
  </>;
}
