import {useState} from 'react';
import type {PageData} from '../api';
interface Component {logical_name:string; source_type:string; repository?:string; chart_name?:string; version?:string; resolved_version?:string; chart_app_version?:string; status:string; reason?:string; scan_job_id?:string; acquisition_diagnostic?: {acquisition_stage?:string; failure_category?:string; attempted_reference?:string; helm_exit_code?:number; safe_stderr_summary?:string; safe_stdout_summary?:string}}
interface DefinitionState {adapter?:string; adapter_label?:string; counts:{declared:number; normalized?:number; unsupported?:number; unresolved?:number}; components:Component[]; run_history?:{run_id:string; components:Component[]}[]}
interface Definition {id:number; source_reference:string; revision_count:number; source_metadata:DefinitionState}
interface DefinitionsData extends PageData {service:{id:number; name:string; service_key:string}; may_edit:boolean; definitions:Definition[]; preview?:DefinitionState; preview_filename?:string; preview_token?:string}
function Components({rows,preview=false,query='',filter='all'}:{rows:Component[]; preview?:boolean; query?:string; filter?:string}) {
  return <table className="definition-components"><thead><tr>{['Component','Source','Chart','Requested Version','Resolved Version','Status'].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{rows.map((row,i)=> {
    const d=row.acquisition_diagnostic; const matches=filter==='all'||filter===row.source_type||(filter==='failed'&&row.status.endsWith('_failed'))||(filter==='unsupported'&&['unsupported','unresolved'].includes(row.status))||(filter==='complete'&&row.status==='complete');
    const text=[row.logical_name,row.source_type,row.repository,row.chart_name,row.version,row.resolved_version,row.chart_app_version,row.status,row.reason,d?.acquisition_stage,d?.failure_category,d?.attempted_reference,d?.helm_exit_code,d?.safe_stderr_summary||d?.safe_stdout_summary,row.scan_job_id].filter(v=>v!=null).join(' ').toLowerCase();
    return <tr key={i} hidden={!matches||!text.includes(query.toLowerCase())}><td>{row.logical_name}</td><td>{row.source_type}{row.repository&&<><br/><small>{row.repository}</small></>}</td><td>{row.chart_name||'—'}</td><td>{row.version||'—'}</td><td>{preview?'—':<>{row.resolved_version||'—'}{row.chart_app_version&&<><br/><small>Chart appVersion: {row.chart_app_version}</small></>}</>}</td><td>{row.status}{row.reason&&`: ${row.reason}`}{!preview&&d&&<details><summary>Acquisition details</summary><small>Stage: {d.acquisition_stage}<br/>Category: {d.failure_category}<br/>Reference: {d.attempted_reference}<br/>Helm exit: {d.helm_exit_code??'—'}<br/>{d.safe_stderr_summary||d.safe_stdout_summary||''}</small></details>}{!preview&&row.scan_job_id&&<><br/><a href={`/scan?job_id=${encodeURIComponent(row.scan_job_id)}`}>Scan {row.scan_job_id.slice(0,8)} (rendered images)</a></>}</td></tr>;
  })}</tbody></table>;
}
function Retained({item,data,root}:{item:Definition;data:DefinitionsData;root:string}) {
  const [query,setQuery]=useState(''); const [filter,setFilter]=useState('all'); const state=item.source_metadata;
  return <article><h3>{item.source_reference}</h3><p>Adapter: {state.adapter} · Declared: {state.counts.declared} · Revision: {item.revision_count}</p>{data.may_edit&&<form method="post" action={`${root}/${item.id}/reprocess`}><input type="hidden" name="csrf_token" value={data.csrf_token||''}/><button type="submit">Reprocess retained original</button></form>}<label>Search components <input type="search" className="definition-search" placeholder="Name, chart or source" value={query} onChange={e=>setQuery(e.target.value)}/></label><label>Filter <select className="definition-filter" value={filter} onChange={e=>setFilter(e.target.value)}>{['all','helm','oci','unsupported','failed','complete'].map(value=><option key={value} value={value}>{value==='oci'?'OCI':value==='helm'?'Helm':value[0].toUpperCase()+value.slice(1)}</option>)}</select></label><Components rows={state.components} query={query} filter={filter}/>{!!state.run_history?.length&&<details><summary>Previous assessment runs ({state.run_history.length})</summary>{state.run_history.map((run,i)=><section key={i}><h4>Run {run.run_id.slice(0,8)}</h4><table><thead><tr>{['Component','Requested Version','Resolved Version','Status'].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{run.components.map((row,j)=><tr key={j}><td>{row.logical_name}</td><td>{row.version||'—'}</td><td>{row.resolved_version||'—'}</td><td>{row.status}</td></tr>)}</tbody></table></section>)}</details>}</article>;
}
export function Page({data:raw}:{data:PageData}) {
  const data=raw as DefinitionsData; const service=`/services/${encodeURIComponent(data.service.service_key)}`; const root=`${service}/definitions`;
  return <><a className="back" href={service}>← {data.service.name}</a><section className="heading"><div><p className="eyebrow">{data.service.service_key}</p><h1>Service definitions / chart catalogs</h1><p>Upload a definition to preview every declared component. CATS retains the original, resolves requested chart versions (including latest), and scans each acquired chart. Singularity enabled values never change scan scope.</p></div></section>{data.may_edit&&<form method="post" encType="multipart/form-data" action={`${root}/preview`}><input type="hidden" name="csrf_token" value={data.csrf_token||''}/><label>Adapter <select name="adapter"><option value="auto">Auto detect</option><option value="singularity">Singularity</option></select></label><label>YAML definition <input type="file" name="upload" accept=".yaml,.yml" required/></label><button type="submit">Preview definition</button></form>}
  {data.preview&&<section><h2>Preview: {data.preview_filename}</h2><p>Adapter: {data.preview.adapter_label} · Declared: {data.preview.counts.declared} · Chart sources: {data.preview.counts.normalized} · Unsupported: {data.preview.counts.unsupported} · Unresolved: {data.preview.counts.unresolved}</p><form method="post" action={`${root}/confirm/${encodeURIComponent(data.preview_token||'')}`}><input type="hidden" name="csrf_token" value={data.csrf_token||''}/><button>Retain and process all components</button></form><Components rows={data.preview.components} preview/></section>}
  <section><h2>Retained definitions</h2>{data.definitions.length?data.definitions.map(item=><Retained key={item.id} item={item} data={data} root={root}/>):<p>No retained definitions yet.</p>}</section></>;
}
