import {afterEach, describe, expect, it, vi} from 'vitest';
import {cleanup, fireEvent, render, screen, waitFor} from '@testing-library/react';
import {Page} from './validators';
import {requestJson} from '../api';
vi.mock('../api', async () => ({...await vi.importActual('../api'),requestJson:vi.fn()}));
afterEach(() => {cleanup();vi.clearAllMocks();vi.useRealTimers();});
const row = {id:1,name:'Lab validator',host:'10.0.0.5',status:'NEW',fingerprint:'SHA256:trusted',fingerprint_confirmed:true,preflight:{status:'supported_with_warnings',facts:{os:'ubuntu',os_version:'22.04',memory_bytes:8589934592},checks:{docker:true,platform:true},warnings:['Firewall requires access']}};
const data = {csrf_token:'csrf',validators:[row],image_readiness:{ready:true},can:Object.fromEntries(['view','add','preflight','provision','test','selftest','cancel','remove'].map(action => [`validator.${action}`,{'*':true}]))};
describe('managed validators', () => {
 it('renders organized host facts, checks and separate health/self-test', () => {render(<Page data={data}/>);expect(screen.getByText('22.04')).toBeTruthy();expect(screen.getByText('8.0 GiB')).toBeTruthy();expect(screen.getAllByText('Passed')).toHaveLength(2);expect(screen.getByText('API health')).toBeTruthy();expect(screen.getByText('Validation self-test')).toBeTruthy();expect(screen.getByRole('button',{name:'Provision validator'})).toHaveProperty('disabled',true);});
 it('clears credentials even when a bootstrap operation fails', async () => {vi.mocked(requestJson).mockRejectedValueOnce(new Error('SSH unavailable'));render(<Page data={data}/>);const password=screen.getByLabelText('Temporary password');fireEvent.change(password,{target:{value:'secret'}});fireEvent.click(screen.getByRole('button',{name:'Test SSH and run preflight'}));expect(password).toHaveProperty('value','');await waitFor(() => expect(screen.getByRole('alert').textContent).toBe('SSH unavailable'));const body=vi.mocked(requestJson).mock.calls[0][1]?.body as FormData;expect(body.get('password')).toBe('secret');expect(body.get('csrf_token')).toBe('csrf');});
 it('switches authentication inputs and clears previous credentials', () => {render(<Page data={data}/>);fireEvent.change(screen.getByLabelText('Temporary password'),{target:{value:'secret'}});fireEvent.change(screen.getByLabelText('Authentication method'),{target:{value:'private_key'}});expect(screen.queryByLabelText('Temporary password')).toBeNull();expect(screen.getByLabelText('Temporary SSH private key')).toHaveProperty('value','');fireEvent.change(screen.getByLabelText('Authentication method'),{target:{value:'password'}});expect(screen.getByLabelText('Temporary password')).toHaveProperty('value','');});
 it('requires explicit fingerprint confirmation before preflight', () => {render(<Page data={{...data,validators:[{...row,fingerprint_confirmed:false}]}}/>);expect(screen.getByRole('button',{name:'Confirm fingerprint'})).toHaveProperty('disabled',true);expect(screen.getByRole('button',{name:'Test SSH and run preflight'})).toHaveProperty('disabled',true);fireEvent.click(screen.getByLabelText('I verified this fingerprint with the host administrator'));expect(screen.getByRole('button',{name:'Confirm fingerprint'})).toHaveProperty('disabled',false);});
 it('submits removal bootstrap credentials and clears them', async () => {vi.mocked(requestJson).mockResolvedValueOnce({validator:{...row,status:'REMOVING',active_operation_id:9}});render(<Page data={data}/>);const password=screen.getByLabelText('Temporary password');fireEvent.change(password,{target:{value:'removal-secret'}});fireEvent.click(screen.getByLabelText('Confirm removal of Lab validator'));fireEvent.click(screen.getByRole('button',{name:'Remove validator'}));expect(password).toHaveProperty('value','');await waitFor(() => expect(vi.mocked(requestJson)).toHaveBeenCalled());const [url,options]=vi.mocked(requestJson).mock.calls[0];expect(url).toMatch(/\/1\/remove$/);expect((options?.body as FormData).get('password')).toBe('removal-secret');});
 it('polls active operations even when the validator status remains healthy', async () => {vi.mocked(requestJson).mockResolvedValue({validator:{...row,status:'HEALTHY',active_operation_id:7}});render(<Page data={{...data,validators:[{...row,status:'HEALTHY',active_operation_id:7}]}}/>);expect(screen.getByRole('button',{name:'Cancel operation'})).toBeTruthy();expect(screen.getByRole('button',{name:'Run self-test'})).toHaveProperty('disabled',true);await waitFor(() => expect(vi.mocked(requestJson)).toHaveBeenCalledWith('/api/frontend/settings/validators/1'),{timeout:4000});});});